// Code generated by "stringer -type=People --linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Bob-1]
	_ = x[Lily-2]
}

const _People_name = "鲍勃莉莉"

var _People_index = [...]uint8{0, 6, 12}

func (i People) String() string {
	i -= 1
	if i < 0 || i >= People(len(_People_index)-1) {
		return "People(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _People_name[_People_index[i]:_People_index[i+1]]
}
